services:
  xxxbot:
    image: nanssye/xxxbot-pad:latest
    container_name: xxxbot-pad
    restart: unless-stopped
    pull_policy: always # 确保每次都检查并拉取最新的镜像
    ports:
      - "9090:9090"   # 管理后台端口
      - "3000:3000"   # WeTTy终端端口
      - "9011:9011"   # WechatAPIServer端口
    volumes:
      - xxxbot-pad:/app
      - redis_data:/var/lib/redis

volumes:
  redis_data:
    name: redis_data
  xxxbot-pad:
    name: xxxbot-pad
